export { default as Main } from './main';
export { default as Login } from './login';
export { default as Register } from './register';
export { default as Information } from './Information';
export { default as Mypage } from './mypage';
export { default as QnA } from './qna';
export { default as Rservation } from './reservation';
export { default as QnAbody } from './qnabody';
export { default as Admin } from './admin';
